name: Build Docker Image

on:
  # Trigger the workflow on push or pull request to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Add manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (if you're using it)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Lowercase repository name
      - name: Lowercase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ env.REPO }}:latest .

      # Step 5: Push the image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO }}:latest